### ISSUE TITLE
Django 1.10 support: AttributeError: module 'django.db.models' has no attribute 'SubfieldBase'

### ISSUE THREAD

**Issue by m-aciek** [MarkusH/django-dynamic-forms#35]
Package is currently not compatibile with Django 1.10:

		Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fb1f340a598>
		Traceback (most recent call last):
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
		    fn(*args, **kwargs)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
		    autoreload.raise_last_exception()
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
		    six.reraise(*_exception)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
		    raise value.with_traceback(tb)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
		    fn(*args, **kwargs)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
		    apps.populate(settings.INSTALLED_APPS)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
		    app_config.import_models(all_models)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
		    self.models_module = import_module(models_module_name)
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/importlib/__init__.py", line 126, in import_module
		    return _bootstrap._gcd_import(name[level:], package, level)
		  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
		  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
		  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
		  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
		  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
		  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/dynamic_forms/models.py", line 18, in <module>
		    from dynamic_forms.fields import TextMultiSelectField
		  File "/home/maciek/.virtualenvs/ankiety/lib/python3.5/site-packages/dynamic_forms/fields.py", line 13, in <module>
		    class TextMultiSelectField(six.with_metaclass(models.SubfieldBase,
		AttributeError: module 'django.db.models' has no attribute 'SubfieldBase'

**Comment by MarkusH** [comment]
Fixed in [v0.5.2](https://pypi.org/project/django-dynamic-forms/0.5.2/)
