### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by ZoltanOnody** [MarkusH/django-dynamic-forms#40]
Hey, I tried to used the app in one of my project but I run into some issues.

# Example project
 I tried to use the *example* project to see what I can accomplish with this app but I got the following error.
```
$ python manage.py migrate
SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E004) Your URL pattern '' is invalid. Ensure that urlpatterns is a list of url() instances.
	HINT: Try removing the string ''. The list of urlpatterns should not have a prefix string as the first element.
```
So I solved the issue by removing the blank url pattern in `example.urls`.

Then I visited `/admin/` but I got the following error.
```
[21/Jan/2017 22:14:58] "GET /en/admin/ HTTP/1.1" 302 0
Internal Server Error: /en/admin/login/
Traceback (most recent call last):
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/template/response.py", line 84, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/template/response.py", line 68, in resolve_template
    return get_template(template, using=self.using)
  File "/home/zoli/projects/test_django_dynamic_forms2/env/lib/python3.5/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/login.html
```

So I set up the templates in settings.
```
TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, "templates")],
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
        'loaders':[
            ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
            ]),
        ],
    },
}
]
```

It worked, I can now create forms via admin. It says I can find an example at `http://127.0.0.1:8000/example-form/` but I cannot. Actually after 15 minutes I wasn't able to figure out how to render the form itself on the page.

It's really inconvenient if the example doesn't work. 

# Custom project
I was able to install the app without any issues, create forms but again, I cannot figure out how to render them.

----

Could you tell me how can I render my forms? The app itself seems very promising but it needs a better documentation otherwise people won't be able to use it.

**Comment by MarkusH** [comment]
Ah, right, there's this example project. I guess I forgot that exists. I'll update the project to work with the latest Django version. Thanks!

**Comment by TenzinJhopee** [comment]
without url - infront of line of url 

 (r'^logout/$', django.contrib.auth.views.logout, {'next_page': '/'},
        name='logout'),
from 
 url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': '/'},
        name='logout'),
